;-----------------------------------------------------------------------------------------------------------------------------------------------
; PROJECT NAME:	FILTER CODE INC FILE
;DATE:		5 DECEMBER 2025
;VERSION:		1
;CREATOR:		PAYDEN HOSKINS
;COMPANY:	IDAHO STATE UNIVERSITY
;DESCRIPTION:	CODE THAT FILTERS WHAT IS SENT BASED ON NOTE AND ADDRESS DIP SWITCH
;-----------------------------------------------------------------------------------------------------------------------------------------------

#include <xc.inc> 
    
PSECT code
    


        